### ISSUE TITLE
How exactly do we start tuning high level MPC?

### ISSUE THREAD

**Issue by SnShine** [ethz-asl/mav_tools_public#4]
I've read wiki page for tuning: https://github.com/ethz-asl/mav_tools_public/wiki/Controller-Tuning. 

I've collected 1st and 2nd order params as explained. But have no idea of tuning MPC. Randomly messed with Q and R params until it kinda works. Simulated drone is going to the setpoint but it wobbles along roll (1-2hz, 10-20 deg) while doing so.

Couldn't find any resources online to tune MPC for drones. Can you expand more on this part or link any external resources to tune?

**Comment by gajena** [comment]
If you really want to understand it completely, go through these  [publicaltions](https://github.com/ethz-asl/mav_control_rw#overview).
And if you want to take a deep-dive in MPC then refer [this](https://github.com/AerialRobotics-IITK/Wiki/wiki/Model-Predictive-Control-(MPC))
